// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ConvertImage(arg1:string):Promise<void>;

export function OpenFile():Promise<string>;

export function SaveFile():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
