// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImage(arg1) {
  return window['go']['image']['ImageConverter']['ConvertImage'](arg1);
}

export function OpenFile() {
  return window['go']['image']['ImageConverter']['OpenFile']();
}

export function SaveFile() {
  return window['go']['image']['ImageConverter']['SaveFile']();
}

export function SetContext(arg1) {
  return window['go']['image']['ImageConverter']['SetContext'](arg1);
}
