// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertVideo(arg1) {
  return window['go']['video']['VideoConverter']['ConvertVideo'](arg1);
}

export function OpenFile() {
  return window['go']['video']['VideoConverter']['OpenFile']();
}

export function SelectDestDir() {
  return window['go']['video']['VideoConverter']['SelectDestDir']();
}

export function SetContext(arg1) {
  return window['go']['video']['VideoConverter']['SetContext'](arg1);
}
